[build]
  base = "frontend"
  publish = "dist"
  command = "npm run build"

[build.environment]
  VITE_API_URL = "http://51.24.95.130"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
